
-- View são feitas apenas para leitura

CREATE OR REPLACE VIEW VW_CUSTOMERS
AS 
SELECT CUSTOMER_ID,
	FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME,
	EMAIL 
FROM CUSTOMER
WHERE ACTIVEBOOL = TRUE 
ORDER BY CUSTOMER_ID
	

CREATE OR REPLACE VIEW 
VW_CUSTOMERS_TOTAIS_POR_CLIENTE
(CLIENTE,MEDIA,MAXIMO,MINIMO,SOMATORIA)
AS 
SELECT R.CUSTOMER_ID, AVG(P.AMOUNT),MAX(P.AMOUNT),
MIN(P.AMOUNT), SUM(P.AMOUNT)
FROM PAYMENT P INNER JOIN RENTAL R
ON P.RENTAL_ID = R.RENTAL_ID
GROUP BY R.CUSTOMER_ID
ORDER BY R.CUSTOMER_ID

SELECT * FROM VW_CUSTOMERS_TOTAIS_POR_CLIENTE

SELECT * FROM INFORMATION_SCHEMA.VIEWS
WHERE table_name = 'vw_customers';

select pg_get_viewdef('VW_CUSTOMERS',true);

select * from CUSTOMER_LIST;

select * from FILM_LIST;