select * from pg_stat_activity
select * from pg_LOCKS

select * from pg_stat_database

select * from pg_backend_pid()
-- 8336

CREATE TABLE TB_TRAN (ID INT PRIMARY KEY, NAME CHAR(10))

SELECT * FROM TB_TRAN
truncate table TB_TRAN

INSERT INTO TB_TRAN VALUES(1,'A');
INSERT INTO TB_TRAN VALUES(2,'B');
INSERT INTO TB_TRAN VALUES(3,'C');
INSERT INTO TB_TRAN VALUES(4,'D');

 BEGIN TRANSACTION

UPDATE TB_TRAN SET NAME = 'XXX'
WHERE ID = 2

UPDATE TB_TRAN SET NAME = 'XXX'
WHERE ID = 3

 ROLLBACK TRANSACTION

 SET TRANSACTION ISOLATION LEVEL READ COMMITTED
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

 LOCK TABLE TB_TRAN IN SHARE
 LOCK TABLE TB_TRAN IN EXCLUSIVE
 