CREATE TABLE CUSTOMERS(
	ID INT NOT NULL,
	NAME VARCHAR(50)
);

INSERT INTO CUSTOMERS VALUES(1,'A');
INSERT INTO CUSTOMERS VALUES(NULL,'DA');
INSERT INTO CUSTOMERS VALUES(1,NULL);

SELECT * FROM CUSTOMERS

DROP TABLE CUSTOMERS

CREATE TABLE CUSTOMERS(
	ID INT UNIQUE,
	NAME VARCHAR(50)
);


CREATE TABLE CUSTOMERS(
	ID INT PRIMARY KEY,
	NAME VARCHAR(50)
);


CREATE TABLE CUSTOMERS(
	ID INT,
	NAME VARCHAR(50),
	CONSTRAINT PK_CUSTOMERS PRIMARY KEY(ID)
);

CREATE TABLE CUSTOMERS(
	ID INT NOT NULL,
	CPF INT NOT NULL,
	NAME VARCHAR(50),
	CONSTRAINT PK_CUSTOMERS PRIMARY KEY(ID,CPF)
);


CREATE TABLE CUSTOMERS(
	ID INT,
	NAME VARCHAR(50),
	LOCATION_ID INT,
	CONSTRAINT PK_CUSTOMERS PRIMARY KEY(ID),
	CONSTRAINT FK_CUST FOREIGN KEY (LOCATION_ID)
	REFERENCES CITY(CITY_ID)
);

INSERT INTO CUSTOMERS VALUES( 1, 'a' ,471);
INSERT INTO CUSTOMERS VALUES( 2, 'a' ,453);